# Generated by Django 5.2.8 on 2025-12-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_course_alter_payment_lesson"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
