# Generated by Django 5.2.8 on 2026-01-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, default=None, null=True, verbose_name="ссылка на платеж"
            ),
        ),
    ]
